### ISSUE TITLE
Test case Failed HOME - 2

### ISSUE THREAD

**Issue by premsaipotukuchi** [Agro-care/Testing#3]
Buttons not working in Home page 
![image](https://github.com/user-attachments/assets/e3f72eed-d65a-4979-8a45-abcba398acc5)

**Comment by Ishanpathak1** [comment]
Which buttons?

**Comment by premsaipotukuchi** [comment]
Forgot to mention them Explore Crops Find Equipment i don't know  where the problems is with front end or backend

**Comment by Ishanpathak1** [comment]
Explore crops button has been fixed, equipments page is the renting page, and kautiliya will be a better person to do handle that

**Comment by premsaipotukuchi** [comment]
Very good front-end back-end Devs issue resolved
